//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Meeting_App.ORM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Meeting_DBEntities : DbContext
    {
        public Meeting_DBEntities()
            : base("name=Meeting_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_Attendee> tbl_Attendee { get; set; }
        public virtual DbSet<tbl_Meeting> tbl_Meeting { get; set; }
        public virtual DbSet<tbl_User> tbl_User { get; set; }
    }
}
