//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Meeting_App.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_User
    {
        public int Id { get; set; }
        public string First_Name { get; set; }
        public string User_Role { get; set; }
        public string User_Name { get; set; }
        public string Password { get; set; }
        public string Last_Name { get; set; }
    }
}
